spring:
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: authentication-service-otp
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/auth/login, /api/v1/auth/register, /api/v1/auth/resend-otp, /api/v1/pin/reset/request
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 5
                    redis-rate-limiter.burstCapacity: 10
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@ipKeyResolver}"
                - name: CircuitBreaker
                  args:
                    name: authentication-service
                    fallbackUri: forward:/fallback/auth

            - id: authentication-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/v1/auth/verify, /api/v1/auth/refresh, /api/v1/auth/logout, /api/v1/auth/pin, /api/v1/pin/**, /api/v1/sessions/**, /oauth2/jwks4
              filters:
                - name: CircuitBreaker
                  args:
                    name: authentication-service
                    fallbackUri: forward:/fallback/auth

            - id: user-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/v1/user/**, /api/v1/users/**, /api/v1/users/profile/**
              filters:
                - name: ScopeValidation
                  args:
                    requiredScope: FULL_ACCESS
                - name: CircuitBreaker
                  args:
                    name: user-service
                    fallbackUri: forward:/fallback/user

            - id: wallet-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/v1/wallet/**, /api/v1/wallets/**
              filters:
                - name: ScopeValidation
                  args:
                    requiredScope: FULL_ACCESS
                - name: CircuitBreaker
                  args:
                    name: wallet-service
                    fallbackUri: forward:/fallback/wallet

            - id: transaction-service-topup-external
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/topup/inquiry/**, /api/v1/topup/callback/**
              filters:
                - name: ApiKeyAuth
                - name: CircuitBreaker
                  args:
                    name: transaction-service
                    fallbackUri: forward:/fallback/transaction

            - id: transaction-service
              uri: http://localhost:8084
              predicates:
                - Path=/api/v1/transfers/**, /api/v1/transactions/**, /api/v1/quick-transfers/**, /api/v1/topup/**, /api/v1/contacts/**, /api/v1/split-bill-payments/**
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 20
                    redis-rate-limiter.burstCapacity: 50
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userKeyResolver}"
                - name: ScopeValidation
                  args:
                    requiredScope: FULL_ACCESS
                - name: CircuitBreaker
                  args:
                    name: transaction-service
                    fallbackUri: forward:/fallback/transaction

            - id: ml-engine-shortlink
              uri: http://localhost:8086
              predicates:
                - Path=/s/**
              filters:
                # No auth required for short link redirection
                - name: CircuitBreaker
                  args:
                    name: ml-engine
                    fallbackUri: forward:/fallback/ml

            - id: ml-engine-service
              uri: http://localhost:8086
              predicates:
                - Path=/api/v1/split-bill/**, /api/v1/process-receipt, /api/v1/submit-split
              filters:
                - name: RequestRateLimiter
                  args:
                    redis-rate-limiter.replenishRate: 10
                    redis-rate-limiter.burstCapacity: 20
                    redis-rate-limiter.requestedTokens: 1
                    key-resolver: "#{@userKeyResolver}"
                - name: ScopeValidation
                  args:
                    requiredScope: FULL_ACCESS
                - name: CircuitBreaker
                  args:
                    name: ml-engine
                    fallbackUri: forward:/fallback/ml

  data:
    redis:
      host: localhost
      port: 6379

  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks

orange:
  cors:
    allowed-origins:
      - "http://localhost:3000"
      - "http://localhost:5173"
      - "http://localhost:8080"
      - "http://localhost:65468"
      - "https://app-dev.orangebybni.my.id/"

  security:
    ip-blocking-enabled: true
    allow-localhost-blocking: false
    violation-threshold: 10
    violation-window: 5m
    block-duration: 1h
    suspicious-duration: 30m
    suspicious-threshold: 5

  payment:
    bni:
      api-key: ${BNI_API_KEY:bni-api-key-dev}

logging:
  level:
    root: INFO
    com.bni.orange: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.kafka: WARN
    org.springframework.boot.actuate: ERROR
    org.springframework.boot.actuate.endpoint.web: ERROR
    org.springframework.boot.actuate.endpoint: ERROR
