spring:
  datasource:
    url: jdbc:postgresql://postgresql-client.database.svc.cluster.local:5432/orange_wallet_db
    username: ${DB_USERNAME:orange_wallet}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      timeout: 60000
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka.messaging.svc.cluster.local:9092}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka.messaging.svc.cluster.local:9092}
      acks: all
      enable-idempotence: true
      retries: 3
      retry-backoff-ms: 1s
      compression-type: snappy
      reliability:
        max-in-flight-requests-per-connection: 5
        request-timeout: 30s
        delivery-timeout: 2m
      batching:
        linger-ms: 20
        batch-size: 32768
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka.messaging.svc.cluster.local:9092}
      group-id: auth-service-profile-sync
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
      max-poll-interval-ms: 300000
      session-timeout-ms: 30000
      heartbeat-interval-ms: 10000
      concurrency: 3

logging:
  level:
    root: INFO
    com.bni.orange: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.kafka: WARN
    org.hibernate: WARN
    org.springframework.boot.actuate: ERROR