spring:
  threads:
    virtual:
      enabled: true

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    enabled: true
    schemas: auth_oltp
    default-schema: auth_oltp
    locations: classpath:db/migration
    baseline-on-migrate: true
    # Credentials managed via Kubernetes Secrets → Environment Variables
    # Set via: SPRING_FLYWAY_USER and SPRING_FLYWAY_PASSWORD

  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      acks: all
      enable-idempotence: true
      retries: 3
      retry-backoff-ms: 1s
      compression-type: snappy
      reliability:
        max-in-flight-requests-per-connection: 5
        request-timeout: 30s
        delivery-timeout: 2m
      batching:
        linger-ms: 20
        batch-size: 32768
    consumer:
      group-id: auth-service-profile-sync
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      enable-auto-commit: false
      max-poll-records: 100
      max-poll-interval-ms: 300000
      session-timeout-ms: 30000
      heartbeat-interval-ms: 10000
      concurrency: 3

orange:
  jwt:
    access-token-duration: 30d # todo revert
    refresh-token-duration: 30d
    state-token-duration: 5m
  rsa:
    public-key: classpath:keys/public.pem
    private-key: classpath:keys/private.pem
  redis:
    prefix:
      otp: "otp:"
      otp-cooldown: "otp_cooldown:"
      otp-fail-count: "otp_fail_count:"
      otp-locked: "otp_locked:"
      pin-fail-count: "pin_fail_count:"
      pin-locked: "pin_locked:"
      jwt-blacklist: "jwt_blacklist:"
      state-token: "state_token:"
  kafka:
    topics:
      definitions:
        otp-notification:
          name: "notification.otp.whatsapp"
          partitions: 3
          replicas: 1
          compact: false
        user-registered:
          name: "auth.user.registered"
          partitions: 3
          replicas: 1
          compact: true
        user-login:
          name: "user.login.events"
          partitions: 3
          replicas: 1
          compact: false

server:
  port: ${SERVER_PORT:8081}
logging:
  level:
    root: INFO
    com.bni.orange: INFO
    com.bni.orange.users: INFO
    org.springframework.web: WARN
    org.springframework.kafka: WARN
    org.springframework.security: WARN
    com.bni.orange.authentication: INFO
    org.apache.kafka.clients.producer.ProducerConfig: DEBUG
    org.apache.kafka.clients.producer.KafkaProducer: DEBUG
    org.springframework.boot.actuate: ERROR
    org.springframework.boot.actuate.endpoint.web: ERROR
    org.springframework.boot.actuate.endpoint: ERROR

google:
  recaptcha:
    enabled: ${RECAPTCHA_ENABLED:false}
    secret: ${RECAPTCHA_SECRET}
    url: https://www.google.com/recaptcha/api/siteverify
    hostname: ${RECAPTCHA_HOSTNAME:localhost}
    score-threshold: ${RECAPTCHA_SCORE_THRESHOLD:0.5}
