spring:
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:orange.wallet.bni@gmail.com}
    password: ${MAIL_PASSWORD}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka.messaging.svc.cluster.local:9092}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka.messaging.svc.cluster.local:9092}
orange:
  user-service:
    base-url: http://user-service:8080
    timeout: 5s
  waha-client:
    base-url: ${WAHA_BASE_URL:http://waha.orange-wallet.svc.cluster.local:3000}
    api-key: ${WAHA_API_KEY}
    session-name: ${WAHA_SESSION_NAME:default}

logging:
  level:
    root: INFO
    com.bni.orange: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.kafka: WARN
    org.hibernate: WARN
    org.springframework.boot.actuate: ERROR