spring:
  datasource:
    url: jdbc:postgresql://postgresql-client.database.svc.cluster.local:5432/orange_wallet_db
    username: ${DB_USERNAME:orange_wallet}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://authentication-service:8080/oauth2/jwks
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      acks: ${KAFKA_PRODUCER_ACKS:all}
      enable-idempotence: ${KAFKA_PRODUCER_IDEMPOTENCE:true}
      retries: ${KAFKA_PRODUCER_RETRIES:3}
      retry-backoff-ms: ${KAFKA_PRODUCER_RETRY_BACKOFF:1s}
      compression-type: ${KAFKA_PRODUCER_COMPRESSION:snappy}
      reliability:
        max-in-flight-requests-per-connection: ${KAFKA_PRODUCER_MAX_IN_FLIGHT:5}
        request-timeout: ${KAFKA_PRODUCER_REQUEST_TIMEOUT:30s}
        delivery-timeout: ${KAFKA_PRODUCER_DELIVERY_TIMEOUT:2m}
      batching:
        linger-ms: ${KAFKA_PRODUCER_LINGER_MS:20}
        batch-size: ${KAFKA_PRODUCER_BATCH_SIZE:32768}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: transaction-service-quick-transfer-sync
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: ${KAFKA_CONSUMER_MAX_POLL_RECORDS:100}
      max-poll-interval-ms: ${KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS:300000}
      session-timeout-ms: ${KAFKA_CONSUMER_SESSION_TIMEOUT_MS:30000}
      heartbeat-interval-ms: ${KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS:10000}
      concurrency: ${KAFKA_CONSUMER_CONCURRENCY:3}

orange:
  services:
    user-service:
      url: http://user-service:8080
      timeout: 5000
    wallet-service:
      url: http://wallet-service:8080
      timeout: 5000
    authentication-service:
      url: http://authentication-service:8080
      timeout: 5000
  integration:
    bni-va:
      base-url: ${BNI_VA_BASE_URL:https://api-sandbox.bni.co.id}
      client-id: ${BNI_VA_CLIENT_ID:dummy-client-id}
      client-secret: ${BNI_VA_CLIENT_SECRET:secret-key-for-dev}
      timeout: 30s
      mock-enabled: ${BNI_VA_MOCK_ENABLED:true}

logging:
  level:
    root: INFO
    com.bni.orange: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.kafka: WARN
    org.hibernate: WARN
    org.springframework.boot.actuate: ERROR