spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orange_db
    username: mikasa
    password: mikasa
    hikari:
      maximum-pool-size: 15
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      acks: all
      enable-idempotence: true
      retries: 3
      retry-backoff-ms: 1s
      compression-type: snappy
      reliability:
        max-in-flight-requests-per-connection: 5
        request-timeout: 30s
        delivery-timeout: 2m
      batching:
        linger-ms: 20
        batch-size: 32768
    consumer:
      bootstrap-servers: localhost:9092
      group-id: transaction-service-quick-transfer-sync
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
      max-poll-interval-ms: 300000
      session-timeout-ms: 30000
      heartbeat-interval-ms: 10000
      concurrency: 3

orange:
  services:
    user-service:
      url: http://localhost:8082
      timeout: 5000
    wallet-service:
      url: http://localhost:8083
      timeout: 5000
    authentication-service:
      url: http://localhost:8081
      timeout: 5000
  integration:
    bni-va:
      base-url: https://api-sandbox.bni.co.id
      client-id: "dummy-client-id"
      client-secret: "secret-key-for-dev"
      timeout: 30s
      mock-enabled: true

logging:
  level:
    root: INFO
    com.bni.orange: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.boot.actuate: ERROR
    org.springframework.boot.actuate.endpoint.web: ERROR
    org.springframework.boot.actuate.endpoint: ERROR