spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://postgres:5432/orange_db}
    username: ${DB_USERNAME:mikasa}
    password: ${DB_PASSWORD:mikasa}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  security:
    oauth2:
      resource-server:
        jwt:
          jwk-set-uri: http://authentication-service:8081/oauth2/jwks
  data:
    redis:
      host: ${REDIS_HOST:redis}
      port: ${REDIS_PORT:6379}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      acks: ${KAFKA_PRODUCER_ACKS:all}
      enable-idempotence: ${KAFKA_PRODUCER_IDEMPOTENCE:true}
      retries: ${KAFKA_PRODUCER_RETRIES:3}
      retry-backoff-ms: ${KAFKA_PRODUCER_RETRY_BACKOFF:1s}
      compression-type: ${KAFKA_PRODUCER_COMPRESSION:snappy}
      reliability:
        max-in-flight-requests-per-connection: ${KAFKA_PRODUCER_MAX_IN_FLIGHT:5}
        request-timeout: ${KAFKA_PRODUCER_REQUEST_TIMEOUT:30s}
        delivery-timeout: ${KAFKA_PRODUCER_DELIVERY_TIMEOUT:2m}
      batching:
        linger-ms: ${KAFKA_PRODUCER_LINGER_MS:20}
        batch-size: ${KAFKA_PRODUCER_BATCH_SIZE:32768}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
      group-id: user-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: ${KAFKA_CONSUMER_MAX_POLL_RECORDS:100}
      max-poll-interval-ms: ${KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS:300000}
      session-timeout-ms: ${KAFKA_CONSUMER_SESSION_TIMEOUT_MS:30000}
      heartbeat-interval-ms: ${KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS:10000}
      concurrency: ${KAFKA_CONSUMER_CONCURRENCY:3}
      poll-timeout: ${KAFKA_CONSUMER_POLL_TIMEOUT:3000}

orange:
  gcp:
    storage:
      enabled: ${GCS_ENABLED:false}
      bucket-name: ${GCS_BUCKET_NAME:orange-wallet-users-profiles}
      project-id: ${GCP_PROJECT_ID:orange-wallet-project}
      service-account-email: ${GCS_SERVICE_ACCOUNT_EMAIL:orange-wallet-storage@orange-wallet-project.iam.gserviceaccount.com}

logging:
  level:
    root: INFO
    com.bni.orange: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.kafka: WARN
    org.springframework.boot.actuate: ERROR
    org.springframework.boot.actuate.endpoint.web: ERROR
    org.springframework.boot.actuate.endpoint: ERROR
