spring:
  datasource:
    url: jdbc:postgresql://postgresql-client.database.svc.cluster.local:5432/orange_wallet_db
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://authentication-service:8080/oauth2/jwks
  data:
    redis:
      timeout: 60000
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka.messaging.svc.cluster.local:9092}
    producer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka.messaging.svc.cluster.local:9092}
      acks: ${KAFKA_PRODUCER_ACKS:all}
      enable-idempotence: ${KAFKA_PRODUCER_IDEMPOTENCE:true}
      retries: ${KAFKA_PRODUCER_RETRIES:3}
      retry-backoff-ms: ${KAFKA_PRODUCER_RETRY_BACKOFF:1s}
      compression-type: ${KAFKA_PRODUCER_COMPRESSION:snappy}
      reliability:
        max-in-flight-requests-per-connection: ${KAFKA_PRODUCER_MAX_IN_FLIGHT:5}
        request-timeout: ${KAFKA_PRODUCER_REQUEST_TIMEOUT:30s}
        delivery-timeout: ${KAFKA_PRODUCER_DELIVERY_TIMEOUT:2m}
      batching:
        linger-ms: ${KAFKA_PRODUCER_LINGER_MS:20}
        batch-size: ${KAFKA_PRODUCER_BATCH_SIZE:32768}
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:kafka.messaging.svc.cluster.local:9092}
      group-id: wallet-read-updater
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: ${KAFKA_CONSUMER_MAX_POLL_RECORDS:100}
      max-poll-interval-ms: ${KAFKA_CONSUMER_MAX_POLL_INTERVAL_MS:300000}
      session-timeout-ms: ${KAFKA_CONSUMER_SESSION_TIMEOUT_MS:30000}
      heartbeat-interval-ms: ${KAFKA_CONSUMER_HEARTBEAT_INTERVAL_MS:10000}
      concurrency: ${KAFKA_CONSUMER_CONCURRENCY:2}
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_MAIL:orange.wallet.bni@gmail.com}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

app:
  mail:
    from: ${SMTP_MAIL:orange.wallet.bni@gmail.com}
    delete-wallet-confirm-base-url: ${APP_DELETE_WALLET_CONFIRM_URL:https://app.orangebybni.my.id/wallet/delete-confirm}
  internal-user:
    base-url: ${INTERNAL_USER_SERVICE_URL:http://user-service:8080}
    connect-timeout: 5000
    read-timeout: 5
    write-timeout: 5
    max-connections: 100
    pending-acquire-timeout: 45
  wallet-delete:
    secret: ${WALLET_DELETE_SECRET:9evyY2Iopik4onDHa+ygvSoI97DJnUx+2JEOeO9ROUE=}
    ttl-seconds: ${WALLET_DELETE_TTL_SECONDS:86400}

logging:
  level:
    root: INFO
    com.bni.orange: INFO
    org.springframework.web: WARN
    org.springframework.security: WARN
    org.springframework.kafka: WARN
    org.hibernate: WARN
    org.springframework.boot.actuate: ERROR