spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/orange_db
    username: mikasa
    password: mikasa
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      validation-timeout: 5000
      leak-detection-threshold: 60000
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8081/oauth2/jwks
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      bootstrap-servers: localhost:9092
      acks: all
      enable-idempotence: true
      retries: 3
      retry-backoff-ms: 1s
      compression-type: snappy
      reliability:
        max-in-flight-requests-per-connection: 5
        request-timeout: 30s
        delivery-timeout: 2m
      batching:
        linger-ms: 20
        batch-size: 32768
    consumer:
      bootstrap-servers: localhost:9092
      group-id: wallet-read-updater
      auto-offset-reset: earliest
      enable-auto-commit: false
      max-poll-records: 100
      max-poll-interval-ms: 300000
      session-timeout-ms: 30000
      heartbeat-interval-ms: 10000
      concurrency: 2
  mail:
    host: ${SMTP_HOST:smtp.gmail.com}
    port: ${SMTP_PORT:587}
    username: ${SMTP_MAIL}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  level:
    root: INFO
    com.bni.orange: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.springframework.kafka: DEBUG
    org.springframework.boot.actuate: ERROR
    org.springframework.boot.actuate.endpoint.web: ERROR
    org.springframework.boot.actuate.endpoint: ERROR

app:
  mail:
    from: ${SMTP_MAIL:orange.wallet.bni@gmail.com}

    delete-wallet-confirm-base-url: ${APP_DELETE_WALLET_CONFIRM_URL:https://app.orangebybni.my.id/wallet/delete-confirm}
  internal-user:
    base-url: http://orange-user-service:8082
    connect-timeout: 5000
    read-timeout: 5
    write-timeout: 5
    max-connections: 100
    pending-acquire-timeout: 45
  wallet-delete:
    secret: 9evyY2Iopik4onDHa+ygvSoI97DJnUx+2JEOeO9ROUE=
    ttl-seconds: 86400
